export const surpriseMePrompts = [
  'uma poltrona em formato de abacate',
  'uma pintura surrealista de Salvador Dalí de um gato jogando xadrez',
  'ursos de pelúcia fazendo compras em um supermercado no Japão, ukiyo-e',
  'uma pintura a óleo de Matisse de um robô humanoides jogando xadrez',
  'um cientista panda maluco misturando produtos químicos brilhantes, arte digital',
  'uma fotografia macro em 35mm de dois ratos no Havaí, ambos usando pequenos trajes de banho e carregando pranchas de surfe minúsculas, arte digital',
  'uma renderização em 3D de um peixe tropical fofo em um aquário sobre um fundo azul escuro, arte digital',
  'um astronauta relaxando em um resort tropical no espaço, vaporwave',
  'um retrato a óleo de uma capivara vestindo trajes reais medievais e uma coroa ornamentada sobre um fundo escuro',
  'uma janela de vitral retratando um hambúrguer e batatas fritas',
  'um desenho a lápis e aquarela de uma cidade brilhante no futuro com carros voadores',
  'uma área de lounge iluminada pelo sol com uma piscina de água transparente e outra piscina de água rosa translúcida, ao lado de uma grande janela, arte digital',
  'um Shiba Inu que lê seu destino em um hambúrguer gigante, arte digital',
  '"uma lontra do mar com uma pérola na orelha" por Johannes Vermeer',
  'um desenho a óleo pastel de um gato irritado em uma espaçonave',
  'uma pintura de uma raposa no estilo de "Noite Estrelada"',
  'uma tigela de sopa que se parece com um monstro, feita de lã tricotada',
  'um robô de pelúcia sentado contra uma parede amarela',
  'um pôr do sol estilo synthwave sobre a água refletida do mar, arte digital',
  'duas torres futuristas com uma ponte coberta de vegetação exuberante, arte digital',
  'uma renderização em 3D de um balão de ar quente colorido do arco-íris voando acima de um lago refletivo',
  'uma capa de quadrinhos de um super-herói usando fones de ouvido',
  'uma explosão centralizada de pó colorido em um fundo preto',
  'uma foto de um cachorro da raça Samoieda com a língua para fora abraçando um gato siamês branco',
  'uma foto de um monstro de pelúcia branca em um quarto roxo',
  'uma foto da escultura "David" de Michelangelo usando fones de ouvido e discotecando',
  'um samurai montado em um cavalo em Marte, lomografia',
  'um Cadillac moderno e elegante dirigindo pela rodovia Gardiner com o centro de Toronto ao fundo, com um efeito de flare na lente, fotografia de 50mm',
  'uma fotografia realista de uma jovem mulher com olhos azuis e cabelos loiros',
  'um homem em pé na frente de um portal estelar para outra dimensão',
  'Bob Esponja Calça Quadrada no Projeto Blair Witch',
  'um velociraptor trabalhando em uma barraquinha de cachorro-quente, lomografia',
  'um homem caminhando pelas movimentadas ruas de Kowloon à noite, iluminadas por muitas placas de neon brilhantes, lente de 50mm',
  'uma churrasqueira que está viva, no estilo de um filme de animação da Pixar',
  'uma boate futurista de ciborgues, luzes de neon',
  'o tão esperado "Star Wars: Anime Japonês de 1990"',
  'um hambúrguer em forma de cubo de Rubik, fotografia profissional de alimentos',
  'um ouriço estilo Synthwave, Blade Runner Cyberpunk',
  'um astronauta encontrando uma forma de vida alienígena em um planeta distante, fotografia',
  'um dinossauro explorando Cape Town, fotografia',
  'um homem se apaixonando por seu computador, arte digital',
  'uma fotografia de um ciborgue explorando Tóquio à noite, lomografia',
  'Drácula caminhando pelas ruas de Nova York na década de 1920, fotografia em preto e branco',
  'aeroplano estilo Synthwave',
  'um homem caminhando pelas ruas chuvosas de Tóquio, com placas de neon brilhantes, lente de 50mm',
  'um ônibus espacial voando acima de Cape Town, arte digital',
];